// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oubofmldlfcarhpmquwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91Ym9mbWxkbGZjYXJocG1xdXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MDE3MjMsImV4cCI6MjA2MTQ3NzcyM30.20pvTKOxiGoyy9qfe3DgXbf_dNlyFAwj7CBblth5Hy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);